name: backend-telemetry

services:
  mqtt:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "1884:1883"
    volumes:
      - ./broker-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      TZ: America/Sao_Paulo
    ports:
      - "8081:8081"

  app:
    build:
      context: ./app
    restart: unless-stopped
    depends_on:
      - mqtt
      - mongo
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: dc-monitor
      TELEMETRY_TOPIC: dc/telemetry
      PORT: 8080
      TZ: America/Sao_Paulo
      FIRMWARE_FILE: firmware.bin
    ports:
      - "8080:8080"
    volumes:
      - firmware-data:/app/uploads

volumes:
  mosquitto-data:
  mosquitto-log:
  mongo-data:
  firmware-data:
